---
- name: Deploy RKE2
  hosts: masters
  become: yes
  roles:
    - role: lablabs.rke2
  vars:
    rke2_version: v1.35.0+rke2r1
    rke2_download_kubeconf: true
    rke2_download_kubeconf_path: ~/.kube
    rke2_ingress_controller: none
